# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"unpack_int64_list": "01_utils.ipynb",
         "unpack_bytes_list": "01_utils.ipynb",
         "unpack_sample": "01_utils.ipynb",
         "Reader": "01_utils.ipynb",
         "compression_code": "01_utils.ipynb",
         "path": "02_data.ipynb",
         "path_img": "02_data.ipynb",
         "train_fnames": "02_data.ipynb",
         "test_fnames": "02_data.ipynb",
         "get_items": "02_data.ipynb",
         "data": "02_data.ipynb",
         "get_x": "02_data.ipynb",
         "get_y": "02_data.ipynb",
         "splitter": "03_model.ipynb",
         "block": "03_model.ipynb",
         "dls": "03_model.ipynb",
         "net1": "03_model.ipynb",
         "learn1": "04_train.ipynb"}

modules = ["utils.py",
           "data.py",
           "model.py",
           "train.py",
           "validate.py"]

doc_url = "https://fastai.github.io/garden2/"

git_url = "https://github.com/fastai/garden2/tree/master/"

def custom_doc_links(name): return None
