# AUTOGENERATED! DO NOT EDIT! File to edit: 03_model.ipynb (unless otherwise specified).

__all__ = ['splitter', 'block', 'dls', 'net1']

# Cell
from fastai2.vision.all import *
from .utils import *
from .data import *

# Cell
splitter = IndexSplitter(range(12753, len(data)))

# Cell
block = DataBlock(blocks=(ImageBlock, CategoryBlock),
                  get_items=get_items,
                  get_x=get_x,
                  get_y=get_y,
                  splitter=splitter,
                  item_tfms=[Resize(224)],
                  batch_tfms=[*aug_transforms()])

# Cell
dls = block.dataloaders('', bs=64,num_workers=0)

# Cell
net1 = xresnet50(pretrained=False, sa=True, act_cls=Mish)