# AUTOGENERATED! DO NOT EDIT! File to edit: 04_train.ipynb (unless otherwise specified).

__all__ = ['learn1']

# Cell
from fastai2.vision.all import *
from .utils import *
from .data import *
from .model import *

# Cell
learn1 = Learner(dls, net1, opt_func=ranger, metrics=accuracy)
learn1.fit_one_cycle(3, 1e-2)